getwd()
attach(Cars)
qqnorm(HP)
qqline(HP)
summary(Cars)
hist(HP)
plot(HP, MPG)
plot(VOL,MPG)
cor(HP,MPG)
cor(VOL, MPG)
cor(WT, VOL)
plot(WT,VOL)
pairs(Cars)
cor(Cars)
library(car)
model.car <- lm(MPG~VOL+HP+SP+WT)
summary(model.car)
model.carV <- lm(MPG~VOL)
summary(model.carV)
model.carW <- lm(MPG~WT)
summary(model.carW)
model.carC <- lm(MPG~VOL+WT)
summary(model.carC)
vif(model.car)
stepAIC(model.car)
plot(model.car)
influenceIndexPlot(model.car)
model.car1 <- lm(MPG~VOL+HP+SP+WT, data = Cars[-77,])
summary(model.car1)
model.final <- lm(MPG~VOL+HP+SP, data = Cars[-77,])
summary(model.final)

# Additional Topics of Multiple Linear Regression
library(corpcor)
cor(Cars)
cor2pcor(cor(Cars))
avPlots(model.car, id.n=9, id.cex=350, data=cars)
avPlots(model.final, id.n=9, id.cex=350, col= "red")




